### ISSUE TITLE
Replace static mixins with placeholders

### ISSUE THREAD

**Issue by KittyGiraudel** [kenwheeler/guff#1]
It is generally considered bad practice to use a mixin when there is no variable involved. Placeholders are best suited for such a thing since they can merge CSS rules, resulting in a lighter CSS output.

If you really want the end user to use `@include` instead of `@extend`, you can wrap the extend in a mixin.

``` scss
// Clearfix include
%clear {
  &:after {
    content:"";
    display:table;
    clear:both;
  }
}

@mixin clear {
  @extend %clear;
}
```

Same goes for `hide-text`, `inline-list` and `container`.

**Comment by kenwheeler** [comment]
I'm the most placeholder loving dude on the planet. However, go look how they now work with media queries. Hugely disappointing.

**Comment by KittyGiraudel** [comment]
I know. But it's not unusual to clear a lot of things in a project for instance. Using mixins, you'll end up with dozens of code duplications... Hugely disappointing as well.

**Comment by kenwheeler** [comment]
what do you think the fix is here? adding both a placeholder and a mixin, and documenting why to use either or?

**Comment by KittyGiraudel** [comment]
You could have something like this (beware, not simple):

``` scss
// Define the mixin as you currently do
// @param [bool] $extend (true): define whether or not to extend a placeholder
@mixin clear($extend: true) {
  // If $extend is true, extend the placeholder
  @if $extend {
    @extend %clear;
  }
  // If $extend is false, dump mixin content
  @else {
    clear: both;
    // Whatever other CSS rule you want
  }
}

// Define the placeholder
%clear {
  @include clear(false); // With extend set to false, obviously
}
```

Now, here is how you use it:

``` scss
a {
  @include clear;
}

b {
  @include clear;
}

// Scoped in a @media directive
@media print {
  c {
    @include clear(false); // Set `$extend` to false
  }
}
```

This will result in:

``` css
a, b {
  clear: both;
}

@media print {
  c {
    clear: both;
  }
}
```

I think as long as you explain what is `$extend` and when to set it to false, this method ensures you end up with the lightest possible CSS output.
