### ISSUE TITLE
Lighter hide-text

### ISSUE THREAD

**Issue by KittyGiraudel** [kenwheeler/guff#2]
The currently used `hide-text` technique involves computing a 9999px wide box for the browser. While this may not be too much hassle for a recent browser, it still creates some unnecessary CPU usage.

You might want to switch to a lighter `hide-text` technique like:

``` css
.hide-text {
  text-indent: 100%;
  white-space: nowrap;
  overflow: hidden;
}
```

Source: http://www.zeldman.com/2012/03/01/replacing-the-9999px-hack-new-image-replacement/.
